### ISSUE TITLE
Allow F* type abbreviations for Pulse function types (feature request)

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/steel#110]
Say I have some function type defined in F* to describe a low-level Pulse implementation function functionally correct with respect to high-level F* specification function:

```
let impl (f: high -> high) =
(l: low) -> (#h: high) ->
stt low (values_match l h) (fun l' -> values_match l (f h))
```

Then, when I want to implement a Pulse function of this type, I currently cannot use this type directly. I first need to spell out the pre- and post-resources again:

```
fn my_impl' (l: low) (#h: high)
  requires (values_match l h)
  returns l': low
  ensures (values_match l' (my_spec h))
{...}
```

and then, if I want to reuse this function with some combinator taking advantage of this type, I need to wrap it in a function defined in F*:

```
let my_impl : impl my_spec = fun l #h -> my_impl' l #h
```

which then causes issues at extraction (even if marked `inline_for_extraction`)

Is it possible to allow using the `impl` type constructor in Pulse, as is already possible in Steel, e.g.:

```
fn my_impl : impl my_spec = fun l h ->
{...}
```

@nikswamy suggested a first step covering only the computation type (the `stt` part) to abbreviate the `requires`, `returns` and `ensures`, but still leaving the binders out. This could be enough to define `my_impl`, since I cannot avoid those binders anyway. But then I hope these extra binders in the type will not be an obstacle for type unification when `my_impl` is used with (possibly higher-order) combinators.

**Comment by nikswamy** [comment]
We support type abbreviations of Pulse function types now:
https://github.com/FStarLang/steel/blob/main/share/steel/examples/pulse/PulseLambdas.fst#L15-L30
