### ISSUE TITLE
Move Pulse libraries to lib/steel/pulse

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/steel#33]
`share/steel/examples/pulse/dice` is using a `lib` directory, which is slated to become a Pulse library. That lib directory used to be located at `share/steel/examples/pulse/lib`, but the dice Makefiles were hardcoding the full path to that lib directory, so that broke the opam CI (i.e. made share/steel no longer work without the Steel source repository.) Thus, in 9cf5fda9, I moved the latter under `share/steel/examples/pulse/dice/lib`.

Ideally, this `lib` directory should move under `lib/steel/pulse`, and suitable `Pulse` namespaces should be added to those file names. However, when trying that, I hit #18 .

**Comment by nikswamy** [comment]
We've made some progress on this with all pulse user-facing libraries now consolidated in share/steel/examples/pulse/lib

It would be nice to move the current contents of lib/steel/pulse elsewhere. Tahina, you had some proposal for that to be compatible with opam etc.

And then to move the current share/steel/examples/pulse/lib to lib/steel/pulse

**Comment by tahina-pro** [comment]
The new repository for Pulse solves this issue at FStarLang/pulse@a5de32a2638757200d38ca5e693e35871d747449
So, this issue can be closed as completed once #168 is merged.
