### ISSUE TITLE
Pulse `invariant b` and `introduce exists b. ...` patterns erase arguments, making syntax equality checks fail

### ISSUE THREAD

**Issue by meganfrisella** [FStarLang/steel#37]
See https://github.com/FStarLang/steel/blob/megan_pulse_lib/share/steel/examples/pulse/bug-reports/IntroGhost.fst

**Comment by meganfrisella** [comment]
also arises for FStar syntax, e.g.
`exists_ (fun (x:t) -> ... x ... )` 
in this pattern x gets erased.

**Comment by nikswamy** [comment]
These are no longer problems with the new prover. Moved the report with some docs into examples.
