### ISSUE TITLE
Confusing behavior when the last pulse block is not ended properly

### ISSUE THREAD

**Issue by aseemr** [FStarLang/steel#69]
The following code successfully verifies:

~~~
```pulse
ghost
fn test_gtot_app_f (x:GR.ref int) (y:int)
  requires GR.pts_to x full_perm 0
  ensures GR.pts_to x full_perm y
{
  open GR;
  (x := y)
}
```
```pulse
ghost
fn test_gtot_app (x:GR.ref int)
  requires GR.pts_to x full_perm 0
  ensures GR.pts_to x full_perm (f 0)
{
  test_gtot_app_f x 0
}
~~~

Even when the function `f` (used in `test_gtot_app`) is not around. The last pulse block is not terminated, and so perhaps it is ignored.

I was a little confused by this, what should be the behavior here?

**Comment by nikswamy** [comment]
Fixed in F* https://github.com/FStarLang/FStar/commit/24a2016cb35c848b91400b25faf4429f322e1c53
